src/TT.Web/Controllers/CovenantController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading;
using System.Web.Mvc;
using Microsoft.AspNet.Identity;
using TT.Domain;
using TT.Domain.Models;
using TT.Domain.Procedures;
using TT.Domain.Statics;
using TT.Domain.ViewModels;
using TT.Domain.World.Queries;

namespace TT.Web.Controllers
{
    [Authorize]
    public partial class CovenantController : Controller
    {

        public virtual ActionResult MyCovenant()
        {
            var me = PlayerProcedures.GetPlayerFromMembership(User.Identity.GetUserId());
            ViewBag.Player = me;

            CovenantViewModel output;

            output = CovenantProcedures.GetCovenantViewModel(me);
            if (output == null || me.Covenant == null || me.Covenant <= 0)
            {
                TempData["Error"] = "You are not currently in a covenant.";
                return RedirectToAction(MVC.Covenant.CovenantList());
            }

            ViewBag.LocationsControlled = CovenantProcedures.GetLocationControlCount(output.dbCovenant);

            ViewBag.MyMoney = Math.Floor(me.Money);

            ViewBag.ErrorMessage = TempData["Error"];
            ViewBag.SubErrorMessage = TempData["SubError"];
            ViewBag.Result = TempData["Result"];

            ViewBag.IAmCaptain = CovenantProcedures.PlayerIsCaptain(output.dbCovenant, me);

            return View(MVC.Covenant.Views.MyCovenant, output);
        }

        public virtual ActionResult CovenantList()
        {
            var output = CovenantProcedures.GetCovenantsList();

            var me = PlayerProcedures.GetPlayerFromMembership(User.Identity.GetUserId());
            ViewBag.Player = me;

            ViewBag.ErrorMessage = TempData["Error"];
            ViewBag.SubErrorMessage = TempData["SubError"];
            ViewBag.Result = TempData["Result"];

            ViewBag.HasApplication = CovenantProcedures.PlayerHasPendingApplication(me);

            return View(MVC.Covenant.Views.CovenantList, output);
        }

        public virtual ActionResult ApplyToCovenant(int id)
        {
            var me = PlayerProcedures.GetPlayerFromMembership(User.Identity.GetUserId());

            // assert that the covenant actually exists...
            var cov = CovenantProcedures.GetDbCovenant(id);

            if (cov == null)
            {
                TempData["Error"] = "That covenant does not exist.";
                return RedirectToAction(MVC.Covenant.MyCovenant());
            }

            // assert that the player is not currently in a covenant
            if (me.Covenant > 0)
            {
                TempData["Error"] = "You must leave your covenant before you can apply to any new ones.";
                return RedirectToAction(MVC.Covenant.MyCovenant());
            }

            // assert that the player doesn't already have a pending application
            if (CovenantProcedures.PlayerHasPendingApplication(me))
            {
                TempData["Error"] = "You already have an application to a covenant.";
                TempData["SubError"] = "In order to apply to a different covenant you must withdraw your old one first.";
                return RedirectToAction(MVC.Covenant.MyCovenant());
            }

            CovenantProcedures.AddCovenantApplication(me, cov);

            TempData["Result"] = "Your application has been sent.";
            return RedirectToAction(MVC.Covenant.MyCovenant());
        }

        public virtual ActionResult ReviewMyCovenantApplications()
        {
            var me = PlayerProcedures.GetPlayerFromMembership(User.Identity.GetUserId());
            // assert that player is in a covenant
            if (me.Covenant == null || me.Covenant <= 0)
            {
                TempData["Error"] = "You are not in a covenant and cannot accept or deny applications.";
                return RedirectToAction(MVC.Covenant.MyCovenant());
            }

            // assert that the player is a covenant leader or captain
            var myCov = CovenantProcedures.GetDbCovenant((int)me.Covenant);
            if (myCov.LeaderId != me.Id && !CovenantProcedures.PlayerIsCaptain(myCov, me))
            {
                TempData["Error"] = "You are not authorized to review applications.";
                TempData["SubError"] = "Only covenant leaders and captains can accept or reject applications";
                return RedirectToAction(MVC.Covenant.MyCovenant());
            }

            // validations are okay:  return the application list
            var output = CovenantProcedures.GetCovenantApplications(myCov);

            return View(MVC.Covenant.Views.ReviewMyCovenantApplications, output);
        }

        public virtual ActionResult ApplicationResponse(int id, string response)
        {
            var me = PlayerProcedures.GetPlayerFromMembership(User.Identity.GetUserId());
            // assert that player is in a covenant
            if (me.Covenant == null || me.Covenant <= 0)
            {
                TempData["Error"] = "You are not in a covenant and cannot accept or deny applications.";
                return RedirectToAction(MVC.Covenant.MyCovenant());
            }

            // assert that the player is a covenant leader or captain
            var myCov = CovenantProcedures.GetDbCovenant((int)me.Covenant);
            if (myCov.LeaderId != me.Id && !CovenantProcedures.PlayerIsCaptain(myCov, me))
            {
                TempData["Error"] = "You are not authorized to review applications.";
                TempData["SubError"] = "Only covenant leaders and captains can accept or reject applications";
                return RedirectToAction(MVC.Covenant.MyCovenant());
            }

            // assert that the last acceptance wasn't too soon if it's past the first full day of the turn
            var minutesAgo = Math.Abs(Math.Floor(myCov.LastMemberAcceptance.Subtract(DateTime.UtcNow).TotalMinutes));
            if ((PvPWorldStatProcedures.GetWorldTurnNumber() > 144) && minutesAgo < 120)
            {

            }

            // get the application from the database
            var app = CovenantProcedures.GetCovenantApplication(id);
            var submitter = PlayerProcedures.GetPlayer(app.OwnerId);

            // assert that the application is for the same covenant
            if (app.CovenantId != myCov.Id)
            {
                TempData["Error"] = "This application is not for your covenant.";
                return RedirectToAction(MVC.Covenant.MyCovenant());
            }

            // assert that the covenant doesn't already have too many animate players
            if (response == "yes" && submitter.Mobility == PvPStatics.MobilityFull &&
                CovenantProcedures.GetPlayerCountInCovenant(myCov, true) >= PvPStatics.Covenant_MaximumAnimatePlayerCount)
            {
                TempData["Error"] = "The maximum number of animate players in your covenant has already been reached.";
                TempData["SubError"] = "You will not be able to accept this player's covenant request until there is room in the covent or they are no longer animate.";
                return RedirectToAction(MVC.Covenant.MyCovenant());
            }

            // assert that the applicant is not currently in a different covenant (e.g. of their own creation)
            if (submitter.Covenant != null || submitter.Covenant >0)
            {
                PlayerLogProcedures.AddPlayerLog(app.OwnerId, "<b style='color: red;'>Your application for " + myCov.Name + " covenant has been revoked as you are currently a member of a different covenant. Please leave your existing covenant before applying to a new one.</b>", true);
                TempData["Error"] = "This player is already in another covenant, thus the application was revoked.";

                CovenantProcedures.RevokeApplication(submitter);
                
                return RedirectToAction(MVC.Covenant.MyCovenant());
            }

            if (response == "yes")
            {

                CovenantProcedures.AddPlayerToCovenant(app.OwnerId, myCov.Id);
                PlayerLogProcedures.AddPlayerLog(app.OwnerId, "<b style='color: blue;'>Congratulations, you have been accepted into the " + myCov.Name + " covenant.</b>", true);
                TempData["Result"] = "You have accepted the application.";

                CovenantProcedures.SetLastMemberJoinTimestamp(myCov);

            }
            else
            {
                PlayerLogProcedures.AddPlayerLog(app.OwnerId, "<b style='color: red;'>Unfortunately, you have not been accepted into the " + myCov.Name + " covenant.</b>", true);
                TempData["Result"] = "You have rejected the application.";
            }

            CovenantProcedures.RevokeApplication(submitter);

            return RedirectToAction(MVC.Covenant.MyCovenant());
        }

        public virtual ActionResult LeaveCovenant()
        {
            var me = PlayerProcedures.GetPlayerFromMembership(User.Identity.GetUserId());

            // assert player is indeed in a covenant
            if (me.Covenant <= 0)
            {
                TempData["Error"] = "You can't leave a covenant because you are not currently in one.";
                return RedirectToAction(MVC.Covenant.MyCovenant());
            }

            CovenantProcedures.RemovePlayerFromCovenant(me);
            TempData["Result"] = "You have left your covenant.";

            return RedirectToAction(MVC.Covenant.MyCovenant());
        }


        public virtual ActionResult ChangeNoticeboardMessage()
        {
            var me = PlayerProcedures.GetPlayerFromMembership(User.Identity.GetUserId());
            // assert that player is in a covenant
            if (me.Covenant == null || me.Covenant <= 0)
            {
                TempData["Error"] = "You are not in a covenant and cannot change the covenant's noticeboard.";

src/TT.Web/Views/Covenant/ChangeCovenantDescription.cshtml
@model TT.Domain.Models.Covenant
@using TT.Domain.Statics
@using TT.Domain.Procedures
@{
    ViewBag.Title = "Change Covenant Description";
}

@section menu
{
    <li><a href="@Url.Action(MVC.PvP.Play())">Back to game</a></li>
    <li><a href="@Url.Action(MVC.Covenant.MyCovenant())">Back to My Covenant</a></li>
}
<div class="containerInner">
    <h3>Coven Settings</h3>

    <p>You can change the settings of your covenant here.</p>
    <br>
    @using (Html.BeginForm(MVC.Covenant.ChangeCovenantDescriptionSubmit(), FormMethod.Post))
    {
        <input type="submit" value="Save changes" class="btn btn-primary">
        <h4>Coven Name</h4>
        @Html.TextBoxFor(m => m.Name, new { maxlength = "50" })
        <hr>
        <h4>Coven Description</h4>
        <span class="charCounter label label-info" id="textRemainingDescription"></span>
        @Html.TextAreaFor(m => m.SelfDescription, new { @class = "form__panel textarea", maxlength = "200", autofocus = true })
        <hr>
        <h4>Coven Blurb</h4>
        <p>Your coven blurb can be up to 250 characters and will display under the room description of your safeground at <b>
            @if(!string.IsNullOrEmpty(Model.HomeLocation))
            {
                @LocationsStatics.LocationList.GetLocation.FirstOrDefault(l => l.dbName == Model.HomeLocation).Name
            }
            else
            {
                <i>... well, you might have a safeground some day</i>
            }
        .</b></p>
        <span class="charCounter label label-info" id="textRemainingBlurb"></span>
        @Html.TextAreaFor(m => m.CovenBlurb, new { @class = "form__panel textarea", maxlength = "250" })
        <hr>
        <h4>Coven Mascot</h4>
        <p>You can nominate a mascot for your coven! Just select the option below.</p>
        <select name="selectMascot" id="selectMascot" class="form__panel select selectMascot">
            <option value="0">None</option>
            @foreach (var p in CovenantProcedures.GetCovenantViewModel(Model.Id).Members)
            {
                <option value="@p.Player.Id" @(p.Player.Id == Model.CovenMascot ? "selected" : "")>
                    @p.Player.FirstName @p.Player.LastName
                </option>
            }
        </select>
        <hr>
        <h4>Coven Flag</h4>
        <p>Choose a flag for your covenant from the options below.</p>

        @*<p>Set flag</p>
            @Html.DropDownListFor(m => m.FlagUrl, new SelectList(
                     new List<Object>{
                          new { value = "region"  , text = "1"  },
                          new { value = "location"  , text = "Location"  },
                       },
                     "value",
                     "text",
                      2))*@

        <img src="https://images.transformaniatime.com/CovenantFlags/bars1.jpg" width="150px" width="150px" id="choice">

        foreach (string s in ViewBag.FlagURLS)
        {
            <img src="https://images.transformaniatime.com/CovenantFlags/@s" height="50px" width="50px" class="selectable" filename="@s">
        }


        @Html.HiddenFor(m => m.Id)
        @Html.HiddenFor(m => m.FlagUrl)
        @Html.HiddenFor(m => m.LastMemberAcceptance)
        @Html.HiddenFor(m => m.IsPvP)
        @Html.HiddenFor(m => m.LeaderId)
        @Html.HiddenFor(m => m.CovenMascot)
        <hr>
        <input type="submit" value="Save changes" class="btn btn-primary">
    }

</div>

@section scripts
{
    <script>
    $(".selectable").click(function () {
        var img = $(this).attr("src");
        var filename = $(this).attr("filename")
       // alert(img);
        $("#choice").attr("src", img);
        $("#FlagUrl").val(filename);
    });

    $(".selectMascot").change(function () {
        var covenmember = $(this).val()
        $("#CovenMascot").val(covenmember);
    });

    $(document).ready(function () {
        var max = 200;
        $('#textRemainingDescription').html(max + ' characters remaining');

        $('#SelfDescription').on('input', function () {
            var length = $(this).val().length;
            var remaining = max - length;

            $('#textRemainingDescription').html(remaining + ' characters remaining');
        });
    });

    $(document).ready(function () {
        var max = 250;
        $('#textRemainingBlurb').html(max + ' characters remaining');

        $('#CovenBlurb').on('input', function () {
            var length = $(this).val().length;
            var remaining = max - length;

            $('#textRemainingBlurb').html(remaining + ' characters remaining');
        });
    });
    </script>
}

@section head
{
    <style>
    .selectable:hover{
        border:2px solid red;
    }
    </style>
}

src/TT.Web/Views/Covenant/ChangeNoticeboardMessage.cshtml
@model TT.Domain.Models.Covenant
@{
    ViewBag.Title = "Change Noticeboard Message";
}

@section menu
{
    <li><a href="@Url.Action(MVC.PvP.Play())">Back to game</a></li>
    <li><a href="@Url.Action(MVC.Covenant.MyCovenant())">Back to My Covenant</a></li>
}
<div class="containerInner">
    <h3>Change Noticeboard Message</h3>

    <p>Noticeboard message will be visible to all coven members on the covenant page.</p>

    @using (Html.BeginForm(MVC.Covenant.ChangeNoticeboardMessageSubmit(), FormMethod.Post))
    {
        @Html.TextAreaFor(m => m.NoticeboardMessage, new { @class = "form__panel textarea", autofocus = true })

        <input type="submit" value="Save">

        @Html.HiddenFor(m => m.Name)
        @Html.HiddenFor(m => m.Id)
        @Html.HiddenFor(m => m.FlagUrl)
        @Html.HiddenFor(m => m.LastMemberAcceptance)
        @Html.HiddenFor(m => m.IsPvP)
        @Html.HiddenFor(m => m.LeaderId)
        @Html.HiddenFor(m => m.SelfDescription)
    }

</div>

src/TT.Web/Views/Covenant/ClaimLocation.cshtml
@{
    ViewBag.Title = "Claim Safeground";
}

@section menu
{
    <li><a href="@Url.Action(MVC.PvP.Play())">Back to game</a></li>
    <li><a href="@Url.Action(MVC.Covenant.MyCovenant())">Back to My Covenant</a></li>
}

<div class="containerInner">

    <h3>Claim This Location as Covenant Safeground</h3>

    <p>As the leader of your covenant, you can choose to claim your current location as a covenant safeground as long as it is not in the streets and you have enough Arpeyjis in your covenant's coffers.  Once you do this, you will not be able to move for the remainder of the round.  Covenant safegrounds can be decorated and upgraded with special furniture that offers special benefits to you and your members. Your covenant must have at least five players who are animate and at level three or higher to do this.</p>

    <p>Would you like to claim this location, <b>@ViewBag.MyLocation</b>, and set it as your covenant's homebase?</p>

    <p>You have <b>@ViewBag.CovenantMoney</b> Arpeyjis in your Covenant's chest.  You will need 2,500.</p>

    <p><a href="@Url.Action(MVC.Covenant.ClaimLocationSend())">Claim this location (2,500 Arpeyjis)</a></p>
</div>

src/TT.Web/Views/Covenant/CovenantLeaderAdmin.cshtml
@{
    ViewBag.Title = "Covenant Administration";
}

@section menu
{
    <li><a href="@Url.Action(MVC.PvP.Play())">Back to game</a></li>
    <li><a href="@Url.Action(MVC.Covenant.MyCovenant())">Back to My Covenant</a></li>
}

<div class="containerInner">

    <h3>Covenant Administration</h3>

    <p>You can administer your covenant here.  When you expand your covenant safeground you increase your covenant's level by 1 which allows it to hold more furniture and increase the action point refill bonus from resting in the covenant's safeground.</p>

    @{
        if (ViewBag.LeaderOrCaptain == "leader")
        {
        <p>
            <a href="@Url.Action(MVC.Covenant.ReviewMyCovenantApplications())">View Applications</a><br>
            <a href="@Url.Action(MVC.Covenant.ChangeCovenantDescription())">Change Covenant Settings</a><br>
            <a href="@Url.Action(MVC.Covenant.InviteCaptainList())">Promote a member to a captain</a><br>
            <a href="@Url.Action(MVC.Covenant.InviteLeaderList())">Promote a member to a leader</a><br>
            <a href="@Url.Action(MVC.Covenant.KickList())">Kick Out a Member</a><br>
            <a href="@Url.Action(MVC.Messages.CovenantWideMessage())">Message all members of your covenant</a><br>
            <a href="@Url.Action(MVC.Covenant.ChangeNoticeboardMessage())">Update the noticeboard message</a><br>
            <a href="@Url.Action(MVC.Covenant.ClaimLocation())">Claim your location as a Covenant safeground</a><br>
            <a href="@Url.Action(MVC.Covenant.UpgradeSafeground())">Expand Covenant Safeground (@ViewBag.UpgradeCost Arpeyjis)</a><br>
        </p>
        }
    }
</div>

src/TT.Web/Views/Covenant/CovenantList.cshtml
@model IEnumerable<TT.Domain.ViewModels.CovenantListItemViewModel>
@using TT.Web.CustomHtmlHelpers
@{
    ViewBag.Title = "List of Covenants";
}

@section menu
{
    <li><a href="@Url.Action(MVC.PvP.Play())">Back to game</a></li>
    @{
        if (ViewBag.Player.Covenant != null)
        {
            <li><a href="@Url.Action(MVC.Covenant.MyCovenant())">Back to My Covenant</a></li>
        }
    }
    <li><a href="@Url.Action(MVC.Covenant.StartNewCovenant())">Create your own Covenant</a></li>
    @{
        if (ViewBag.HasApplication)
        {
            <li><a href="@Url.Action(MVC.Covenant.WithdrawApplication())">Withdraw Coven Application</a></li>
        }
    }
}

<div class="containerInner">
    @{
        foreach (var c in Model.OrderByDescending(c => c.MemberCount))
        {
            <div class="covListing">
                <div class="covFlag" style="background-image: url(https://images.transformaniatime.com/CovenantFlags/@c.dbCovenant.FlagUrl)"></div>
                <span class="covBigName"><a href="@Url.Action(MVC.Covenant.LookAtCovenant(c.dbCovenant.Id))">@c.dbCovenant.Name</a></span>
                <span>(lvl @c.dbCovenant.Level)</span>
                <span class="covMemberCount">(@c.MemberCount members, @c.AnimateMemberCount animate)</span>
                <span class="covLeader"><a href="@Url.Action(MVC.PvP.LookAtPlayer(c.Leader.Id))">Led by @c.Leader.GetFullName()</a></span>

                <p>@c.dbCovenant.SelfDescription.  @HtmlHelpers.PrintCovenantSafeground(c.dbCovenant)</p>

                @{
                    if (ViewBag.Player.Covenant == null)
                    {
                        <a href="@Url.Action(MVC.Covenant.ApplyToCovenant(c.dbCovenant.Id))">Apply</a>
                    }
                }
            </div>
        }
    }
</div>

src/TT.Web/Views/Covenant/CovenantWideMessage.cshtml
<nav class="navbar navbar-default outsideContainer navbarTT2">
    <div class="container-fluid">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-2">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
        </div>

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-2">
            <ul class="nav navbar-nav">
                <li>@Html.ActionLink("Back to game", "Play", "PvP")</li>
                <li>@Html.ActionLink("Back to My Covenant", "MyCovenant", "Covenant")</li>
            </ul>
        </div><!-- /.navbar-collapse -->
    </div><!-- /.container-fluid -->
</nav>
<div class="containerInner">

    @model TT.Domain.ViewModels.PublicBroadcastViewModel

    <h3>Covenant-Wide Message</h3>

    <p>You can send a message to all members of your covenant here.</p>

    @using (Html.BeginForm("SendCovenantWideMessage", "Covenant", FormMethod.Post))
    {
        @Html.TextAreaFor(m => m.Message)
        <br />
        <input type="submit" value="Send" />
    }

</div>

src/TT.Web/Views/Covenant/InviteCaptainList.cshtml
@model TT.Domain.ViewModels.CovenantViewModel
@{
    ViewBag.Title = "Covenant Captains";
}

@section menu
{
    <li><a href="@Url.Action(MVC.PvP.Play())">Back to game</a></li>
    <li><a href="@Url.Action(MVC.Covenant.MyCovenant())">Back to My Covenant</a></li>
}

<div class="containerInner">
    <h3>Add or Remove a Covenant Captain</h3>
    <p>Click on one of the names below to add a member of the covenant as a captain.  If they are currently a captain, clicking on their name will remove that status.</p>
    <p>Covenant captains are special trusted members of the covenant and are permitted to purchase furniture and gift out covenant funds. They can also edit the coven noticeboard.</p>
    @{
        foreach (var p in Model.Members)
        {
            <p>
                <a href="@Url.Action(MVC.Covenant.InviteCaptainSend(p.Player.Id))">@p.Player.GetFullName()</a>
                @{
            if (ViewBag.CurrentCaptains.Contains(p.Player.Id + ";"))
            {
                <span class="good">Current Captain</span>
            }
                }
            </p>
        }
    }
</div>

src/TT.Web/Views/Covenant/InviteLeaderList.cshtml
@model TT.Domain.ViewModels.CovenantViewModel
@{
    ViewBag.Title = "Set New Covenant Leader";
}

@section menu
{
    <li><a href="@Url.Action(MVC.PvP.Play())">Back to game</a></li>
    <li><a href="@Url.Action(MVC.Covenant.MyCovenant())">Back to My Covenant</a></li>
}

<div class="containerInner">
    <h3>Set a new Covenant Leader</h3>
    <p>Click on one of the names below to set a member of the covenant as the leader.</p>
    <p>Covenant leaders are the highest trusted member of the covenant and are permitted all covenant administrative access. Setting a new covenant leader will revoke your leadership status.</p>
    @{
        foreach (var p in Model.Members)
        {
            <p>
                <a href="@Url.Action(MVC.Covenant.InviteLeaderSend(p.Player.Id))">@p.Player.GetFullName()</a>
            </p>
        }
    }

</div>

src/TT.Web/Views/Covenant/LookAtCovenant.cshtml
@model TT.Domain.ViewModels.CovenantViewModel
@using TT.Domain.Statics
@using TT.Domain.Procedures
@{
    ViewBag.Title = "Look at Covenant";
}


@section menu
{
    <li><a href="@Url.Action(MVC.PvP.Play())">Back to game</a></li>
    @{
        if (ViewBag.Player.Covenant != null)
        {
            <li><a href="@Url.Action(MVC.Covenant.MyCovenant())">Back to My Covenant</a></li>
        }
    }
    <li><a href="@Url.Action(MVC.Covenant.CovenantList())">View All Covenants</a></li>
    @{
        if (User.IsInRole(PvPStatics.Permissions_Moderator) || User.IsInRole(PvPStatics.Permissions_Admin))
        {
            <li><a href="@Url.Action(MVC.Chat.ChatLog($"coven_{Model.dbCovenant.Id}", "lasth"))" target="_blank">Moderate Chat</a></li>
        }
    }
}

<div class="containerInner text-center">
    <div class="covFlag" style="background-image: url(https://images.transformaniatime.com/CovenantFlags/@Model.dbCovenant.FlagUrl)"></div>
    @if (Model.dbCovenant.CovenMascot > 0)
    {
        <a class="mascot" style="background-image: url(@TT.Web.CustomHtmlHelpers.HtmlHelpers.GetImageURL(PlayerProcedures.GetPlayerFormViewModel(Model.Mascot.Id), true));" href="@Url.Action(MVC.PvP.LookAtPlayer(Model.Mascot.Id))">
        @Model.Mascot.FirstName @Model.Mascot.LastName
        </a>
    }
    <p class="covHeader"><span class="covName">@Model.dbCovenant.Name</span></p><br>
    <p>
        <b>@Model.dbCovenant.SelfDescription</b>
    </p>
    <p>
        @{
            if (!Model.dbCovenant.HomeLocation.IsNullOrEmpty())
            {
                <i>This covenant has a safeground at <b>@LocationsStatics.LocationList.GetLocation.FirstOrDefault(l => l.dbName == Model.dbCovenant.HomeLocation).Name</b> and has enchanted <b>@ViewBag.LocationsControlled</b> locations.</i>
            }
        }
    </p>
    <a href="@Url.Action(MVC.PvP.LookAtPlayer(Model.Leader.Id))">Led by @Model.Leader.GetFullName()</a>

    <p>
        <a href="@Url.Action(MVC.Covenant.ApplyToCovenant(Model.dbCovenant.Id))">Apply to join this covenant</a>
        @{
            if (Model.IsFull)
            {
                <span class="bad">(Currently full!)</span>
            }
        }
    </p>
</div>

<div class="onlinePlayersWrapperBG">
    <div class="row boxContainer">
@foreach (var p in Model.Members.OrderByDescending(c => c.Player.Level).ThenByDescending(c => c.Player.XP))
    {
                <div class="col-md-2 col-sm-4 col-xs-12 charaBox">
                    <div class="charaBoxInner">
                        <div>
                            <p>

                          @Html.Partial(MVC.PvP.Views.Player_Partial, p)
                            </p>
                        </div>
                    </div>
                </div>
      }
    </div>
</div>

src/TT.Web/Views/Covenant/ReviewMyCovenantApplications.cshtml
@model IEnumerable<TT.Domain.ViewModels.CovenantApplicationViewModel>
@using TT.Web.CustomHtmlHelpers
@{
    ViewBag.Title = "Covenant Applications";
}

@section menu
{
    <li><a href="@Url.Action(MVC.PvP.Play())">Back to game</a></li>
    <li><a href="@Url.Action(MVC.Covenant.MyCovenant())">Back to My Covenant</a></li>
}

<div class="containerInner">
    <h3>Review Applications</h3>

    @{
        foreach (var app in Model)
        {
        <p>
            <a href="@Url.Action(MVC.PvP.LookAtPlayer(app.dbPlayer.Id))">@app.dbPlayer.GetFullName()</a> applied @HtmlHelpers.DatetimeToTimeago(app.dbCovenantApplication.Timestamp)
            <a href="@Url.Action(MVC.Covenant.ApplicationResponse(app.dbCovenantApplication.Id, "yes"))">Accept</a>
            <a href="@Url.Action(MVC.Covenant.ApplicationResponse(app.dbCovenantApplication.Id, "no"))">Deny</a>
        </p>
        }

        if (!Model.Any())
        {
            <p><b>You do not have any applications at this time.</b></p>
        }

    }
</div>